// Code generated by mdatagen. DO NOT EDIT.

package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("vali")
	ScopeName = "github.com/gardener/opentelemetry-collector/exporter/valiexporter"
)

const (
	LogsStability = component.StabilityLevelAlpha
)
